apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vulnerability-exporter-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]